CREATE TABLE IF NOT EXISTS users(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(255), email VARCHAR(255) UNIQUE);

CREATE TABLE IF NOT EXISTS requests(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, description VARCHAR(255), created_at TIMESTAMP WITHOUT TIME ZONE, requester_id INT REFERENCES users(id));

CREATE TABLE IF NOT EXISTS items(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, owner_id INT REFERENCES users(id), name VARCHAR(255), description VARCHAR(255), available BOOLEAN, request_id INT REFERENCES requests(id));

CREATE TABLE IF NOT EXISTS comments(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, item_id INT REFERENCES items(id), user_id INT REFERENCES users(id), comment VARCHAR(500), created_at TIMESTAMP WITHOUT TIME ZONE);

CREATE TABLE IF NOT EXISTS bookings(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, start_date TIMESTAMP WITHOUT TIME ZONE, end_date TIMESTAMP WITHOUT TIME ZONE, item_id INT REFERENCES items(id), borrowing_user_id INT REFERENCES users(id), status VARCHAR(255));
